/*----------------D4_2 Hands-on----------------
1) Metadata Cache
2) Results Cache
3) Virtual Warehouse Local Storage
----------------------------------------------*/

-- Set context
USE ROLE SYSADMIN;

USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000;

alter warehouse compute_wh suspend;

alter warehouse set auto_resume= false;
-- Count all records

SELECT COUNT(*) FROM CUSTOMER;

-- Context Functions

SELECT CURRENT_USER();

-- Object descriptions

DESCRIBE TABLE CUSTOMER;
desc  table customer;
-- List objects

show tables;
-- System functions 

SELECT SYSTEM$CLUSTERING_INFORMATION('LINEITEM', ('L_ORDERKEY'));


SELECT * FROM CUSTOMER limit 10;

-- Results Cache

alter warehouse compute_wh resume if suspended;
alter warehouse set auto_resume = true;

SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE FROM CUSTOMER LIMIT 100;

SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE FROM CUSTOMER LIMIT 100;

-- Syntactically different
SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_ACCTBAL FROM CUSTOMER LIMIT 100;

-- Includes functions evaluated at execution time
SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, CURRENT_TIMESTAMP() FROM CUSTOMER LIMIT 100;

USE ROLE ACCOUNTADMIN;

alter account set use_cached_result = false;

SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE FROM CUSTOMER LIMIT 100;

-- Local storage
SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE
FROM ORDERS
WHERE O_ORDERDATE > DATE('1997-09-19')
ORDER BY O_ORDERDATE
LIMIT 10;

SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE
FROM ORDERS
WHERE O_ORDERDATE > DATE('1997-09-19')
ORDER BY O_ORDERDATE
LIMIT 10;


-- Additional column
SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE, O_CLERK, O_ORDERPRIORITY
FROM ORDERS
WHERE O_ORDERDATE > DATE('1997-09-19')
ORDER BY O_ORDERDATE
LIMIT 10;

ALTER WAREHOUSE COMPUTE_WH SUSPEND;
ALTER WAREHOUSE COMPUTE_WH RESUME;

SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE
FROM ORDERS
WHERE O_ORDERDATE > DATE('1997-09-19')
ORDER BY O_ORDERDATE
LIMIT 10;

ALTER ACCOUNT SET USE_CACHED_RESULT = TRUE;